{% set name = "imia" %}
{% set version = "0.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/imia-{{ version }}.tar.gz
  sha256: e02cdebceef1828f076f52477bf78612dabf282ac9334855ffb491576c26bb1f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8
  run:
    - aiosqlite >=0.17.0
    - python >=3.8
    - sqlalchemy >=1.4.25
    - starsessions >=1.0.1

test:
  imports:
    - imia
    - imia.ext
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alex-oleshkevich/imia
  summary: Full stack authentication library for ASGI.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
