{% set name = "imia" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/imia-{{ version }}.tar.gz
  sha256: f4338b5f60e1fc5d6f00516c0742aca4b22ecfd8c184323af6245b7844233050

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.8
  run:
    - aiosqlite >=0.17.0
    - python >=3.8
    - python-multipart >=0.0.5
    - requests >=2.25.1
    - sqlalchemy >=1.4.25
    - starsessions >=1.0.1

test:
  imports:
    - imia
    - imia.ext
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alex-oleshkevich/imia
  summary: Full stack authentication library for ASGI.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
