{% set name = "imia" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/imia-{{ version }}.tar.gz
  sha256: 23d0064dfa59a0b2bd22d3235b0718f8cfdf928f5300aaa9c23bce9b93972027

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8
  run:
    - aiosqlite >=0.17.0
    - python >=3.8
    - sqlalchemy >=1.4.25

test:
  imports:
    - imia
    - imia.ext
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alex-oleshkevich/imia
  summary: Full stack authentication library for ASGI.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
